import React, { useState, useEffect } from 'react';
import {
  Brain, ShoppingCart, AlertTriangle, TrendingDown, Leaf, RefreshCw, Clock, Package
} from 'lucide-react';
import { Button } from '../components/ui/button';
import { Card, CardContent } from '../components/ui/card';
import { Badge } from '../components/ui/badge';
import { useTheme } from '../contexts/ThemeContext';
import { toast } from 'sonner';
import axios from 'axios';

const API = process.env.REACT_APP_BACKEND_URL;
const authHeader = () => ({ Authorization: `Bearer ${localStorage.getItem('ananta_token')}` });

const URGENCY_COLORS = { high: 'bg-red-100 text-red-700', medium: 'bg-amber-100 text-amber-700', low: 'bg-green-100 text-green-700' };
const CAT_ICONS = { Produce: Leaf, Meat: Package, Dairy: Package, Seafood: Package, 'Dry Goods': ShoppingCart, Beverages: ShoppingCart };

export default function AIPantry() {
  const { theme } = useTheme();
  const [pantryData, setPantryData] = useState(null);
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(false);
  const [tab, setTab] = useState('generate');

  useEffect(() => { fetchHistory(); }, []);

  const fetchHistory = async () => {
    try {
      const res = await axios.get(`${API}/api/ai-pantry/history`, { headers: authHeader() });
      setHistory(res.data);
      if (res.data.length > 0) setPantryData(res.data[0]);
    } catch {}
  };

  const generateList = async () => {
    setLoading(true);
    try {
      const res = await axios.get(`${API}/api/ai-pantry/generate`, { headers: authHeader() });
      setPantryData(res.data);
      toast.success('Pantry list generated by AI');
      fetchHistory();
    } catch (e) {
      toast.error(e.response?.data?.detail || 'Failed to generate list');
    }
    setLoading(false);
  };

  const data = pantryData?.data || {};
  const orderingList = data.orderingList || [];
  const wastageInsights = data.wastageInsights || [];

  return (
    <div data-testid="ai-pantry-page">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-3xl font-bold" style={{ color: theme.text }}>AI Smart Pantry</h1>
          <p className="text-gray-500 mt-1">AI-powered weekly ordering with minimum wastage</p>
        </div>
        <Button onClick={generateList} disabled={loading} style={{ backgroundColor: theme.primary }}
          data-testid="generate-pantry-btn">
          {loading ? <><RefreshCw size={18} className="mr-2 animate-spin" /> Analyzing...</> :
            <><Brain size={18} className="mr-2" /> Generate Weekly List</>}
        </Button>
      </div>

      {/* Tabs */}
      <div className="flex gap-2 mb-6">
        {['generate', 'history'].map(t => (
          <button key={t} onClick={() => setTab(t)}
            className={`px-4 py-2 rounded-full text-sm font-medium ${tab === t ? 'bg-gray-900 text-white' : 'bg-gray-100 text-gray-600'}`}>
            {t === 'generate' ? 'Current List' : `History (${history.length})`}
          </button>
        ))}
      </div>

      {tab === 'generate' && (
        <>
          {!pantryData && !loading && (
            <Card className="border-dashed">
              <CardContent className="p-12 text-center">
                <Brain size={48} className="mx-auto mb-4 text-gray-300" />
                <h3 className="text-lg font-semibold text-gray-700">No pantry list yet</h3>
                <p className="text-sm text-gray-500 mt-2">Click "Generate Weekly List" to let AI analyze your menu, sales, and reservations</p>
              </CardContent>
            </Card>
          )}

          {pantryData && (
            <div className="space-y-6">
              {/* Summary */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <Card><CardContent className="p-4 text-center">
                  <p className="text-sm text-gray-500">Items to Order</p>
                  <p className="text-2xl font-bold" style={{ color: theme.primary }}>{orderingList.length}</p>
                </CardContent></Card>
                <Card><CardContent className="p-4 text-center">
                  <p className="text-sm text-gray-500">Est. Budget</p>
                  <p className="text-2xl font-bold text-emerald-600">${data.weeklyBudgetEstimate?.toFixed(2) || '—'}</p>
                </CardContent></Card>
                <Card><CardContent className="p-4 text-center">
                  <p className="text-sm text-gray-500">Cover Forecast</p>
                  <p className="text-2xl font-bold text-blue-600">{data.coverForecast || pantryData.upcomingCovers || '—'}</p>
                </CardContent></Card>
                <Card><CardContent className="p-4 text-center">
                  <p className="text-sm text-gray-500">Wastage Alerts</p>
                  <p className="text-2xl font-bold text-amber-600">{wastageInsights.length}</p>
                </CardContent></Card>
              </div>

              {data.summary && (
                <Card className="bg-blue-50 border-blue-200"><CardContent className="p-4">
                  <p className="text-sm text-blue-800"><Brain size={14} className="inline mr-1" /> <strong>AI Summary:</strong> {data.summary}</p>
                </CardContent></Card>
              )}

              {/* Ordering List */}
              <Card><CardContent className="p-5">
                <h3 className="font-semibold mb-4 flex items-center gap-2">
                  <ShoppingCart size={18} /> Weekly Ordering List
                </h3>
                <div className="space-y-3">
                  {orderingList.map((item, i) => (
                    <div key={i} className="flex items-center gap-4 p-3 rounded-lg bg-gray-50 hover:bg-gray-100" data-testid={`pantry-item-${i}`}>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <p className="font-medium">{item.ingredient}</p>
                          <Badge className={URGENCY_COLORS[item.urgency] || URGENCY_COLORS.low}>{item.urgency}</Badge>
                        </div>
                        <p className="text-xs text-gray-500 mt-0.5">
                          {item.category} &middot; Used in: {item.usedIn?.join(', ') || 'Various'}
                        </p>
                        {item.notes && <p className="text-xs text-gray-400 mt-0.5">{item.notes}</p>}
                      </div>
                      <div className="text-right">
                        <p className="font-bold">{item.estimatedQuantity}</p>
                        {item.estimatedCost > 0 && <p className="text-xs text-gray-400">${item.estimatedCost?.toFixed(2)}</p>}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent></Card>

              {/* Wastage Insights */}
              {wastageInsights.length > 0 && (
                <Card className="border-amber-200"><CardContent className="p-5">
                  <h3 className="font-semibold mb-4 flex items-center gap-2 text-amber-700">
                    <AlertTriangle size={18} /> Wastage Insights
                  </h3>
                  <div className="space-y-3">
                    {wastageInsights.map((w, i) => (
                      <div key={i} className="flex items-start gap-3 p-3 bg-amber-50 rounded-lg">
                        <TrendingDown size={16} className="text-amber-600 mt-0.5 flex-shrink-0" />
                        <div>
                          <p className="font-medium text-sm">{w.item} <Badge className={URGENCY_COLORS[w.risk]}>{w.risk} risk</Badge></p>
                          <p className="text-xs text-gray-600 mt-1">{w.recommendation}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent></Card>
              )}
            </div>
          )}
        </>
      )}

      {tab === 'history' && (
        <div className="space-y-3">
          {history.map(h => (
            <Card key={h.id} className="cursor-pointer hover:shadow-md transition-shadow"
              onClick={() => { setPantryData(h); setTab('generate'); }}>
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <p className="font-medium">{h.id}</p>
                  <p className="text-xs text-gray-500">
                    <Clock size={12} className="inline mr-1" />
                    {new Date(h.generatedAt).toLocaleDateString()} &middot;
                    {h.data?.orderingList?.length || 0} items &middot;
                    {h.menuItemCount} menu items analyzed
                  </p>
                </div>
                <Badge variant="outline">${h.data?.weeklyBudgetEstimate?.toFixed(2) || '—'}</Badge>
              </CardContent>
            </Card>
          ))}
          {history.length === 0 && <p className="text-gray-400 text-center py-8">No history yet</p>}
        </div>
      )}
    </div>
  );
}
